### ISSUE TITLE
Use Encrypted Websockets

### ISSUE THREAD

**Issue by khazhyk** [iabarca/ugc-bot-redux#1]
https://github.com/iabarca/ugc-bot-redux/blob/b1bc87314daf4dbaec8b4842ecb0943759022056/src/main/java/sx/blah/discord/api/internal/DiscordWS.java#L237

Discord is going to disable unencrypted websockets ('ws') in a few minutes. You should use encrypted websockets ('wss')

**Comment by iabarca** [comment]
Thanks, I missed that. That's what I get for just pasting the library's source.

**Comment by iabarca** [comment]
Turns out https://github.com/austinv11/Discord4J has the same issue. Library has the code for wss but that replace line was forgotten. I've forwarded the issue to the developer.
